export const USER = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  LOGOUT_CURRENT_USER: "LOGOUT_CURRENT_USER",
};

export const ADMIN = {
  SET_TEACHERS: "SET_TEACHERS_DATA",
  CLEAR_TEACHERS: "CLEAR_TEACHERS_DATA",
};

export const TEACHER = {
  SET_CLASSROOMS: "SET_CLASSROOMS_DATA",
  CLEAR_CLASSROOMS: "CLEAR_CLASSROOMS_DATA",
};

export const CLASSROOM = {
  SET_STUDENTS: "SET_STUDENTS",
  CLEAR_STUDENTS: "CLEAR_STUDENTS",
};

export const STUDENT = {
  SET_CURRENT_STUDENT: "SET_CURRENT_STUDENT",
  CLEAR_CURRENT_STUDENT: "CLEAR_CURRENT_STUDENT",
};

export const TEST = {
  SET_TEST: "SET_TEST",
  CLEAR_TEST: "CLEAR_TEST",
};
